name: Run scraper

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write
  actions: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.205

    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Checkout thepbone/FirmwareProviderAPI
      uses: actions/checkout@v3
      with:
        repository: ThePBone/FirmwareProviderAPI
        submodules: true
        path: './scraper'
    
    - name: Run scraper
      run: |
        dotnet run --project scraper/FirmwareProviderCLI/
        rm -rf scraper
        rm *.log

    - name: Publish summary changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add new firmware binaries

        
